import type { LearningObjective, LessonDefinition } from './types';

const lo1: LearningObjective[] = ['LO1'];
const lo2: LearningObjective[] = ['LO2'];
const loBoth: LearningObjective[] = ['LO1', 'LO2'];

const supportBase = [
  'Read questions aloud.',
  'Use the picture and the word together.',
  'Allow pointing or verbal answers.',
  'Sentence starters: “I notice ______.” “This is good data because ______.” “AI learns from ______.”',
];

export const lesson1: LessonDefinition = {
  id: 'lesson1',
  number: 1,
  totalLessons: 5,
  title: 'Learning From Data and Patterns',
  missionTitle: 'MISSION 1: TEACH PIXEL HOW TO LEARN',
  durationMinutes: 45,
  bigQuestion: 'How does AI learn?',
  screens: [
    {
      id: 'l1-s01',
      index: 0,
      stage: 'START',
      title: 'Mission Launch',
      studentTitle: 'TEACH PIXEL HOW TO LEARN!',
      objectives: loBoth,
      iCan: 'I can help Pixel learn.',
      strategies: ['Storytelling'],
      recommendedMinutes: 2,
      teacher: {
        time: '2 minutes',
        objectives: loBoth,
        strategy: 'Storytelling + Inquiry',
        script: [
          'Over the next five missions we are going to learn about AI.',
          'Pixel is our AI robot.',
          'Today Pixel needs us to teach it how AI learns.',
        ],
        expectedAnswers: [],
        misconceptions: ['Students may think robots already know everything.'],
        support: supportBase,
        challenge: ['Ask: “What do you think Pixel needs in order to learn?”'],
      },
    },
    {
      id: 'l1-s02',
      index: 1,
      stage: 'START',
      title: "Today's Mission",
      studentTitle: "TODAY'S MISSION",
      objectives: loBoth,
      iCan: 'I can say what I will learn today.',
      strategies: ['Learning intentions'],
      recommendedMinutes: 1,
      teacher: {
        time: '1 minute',
        objectives: loBoth,
        strategy: 'Learning intentions + success criteria',
        script: [
          'Read the three “I can” cards together.',
          'Point to the success stars so children know what “done” looks like.',
        ],
        expectedAnswers: [],
        misconceptions: [],
        support: supportBase,
        challenge: ['Ask a volunteer to restate one goal in their own words.'],
      },
    },
    {
      id: 'l1-s03',
      index: 2,
      stage: 'DISCOVER',
      title: 'Activate Prior Knowledge',
      studentTitle: 'WHAT DO YOU ALREADY KNOW ABOUT AI?',
      objectives: lo1,
      iCan: 'I can notice AI around me.',
      strategies: ['Think–Pair–Share'],
      recommendedMinutes: 3,
      teacher: {
        time: '3 minutes',
        objectives: lo1,
        strategy: 'Think–Pair–Share · Activating prior knowledge',
        script: [
          'Look at these familiar examples.',
          'Where have you seen something smart like this before?',
        ],
        prompts: [
          'What makes you think it is smart?',
          'Does it know everything?',
          'How might it learn?',
        ],
        expectedAnswers: [
          'phones',
          'robots',
          'voice assistants',
          'games',
          'apps',
          'chatbots',
        ],
        misconceptions: [
          'AI is magic.',
          'AI is a person.',
          'AI already knows everything.',
        ],
        support: supportBase,
        challenge: ['Ask: “Is every smart-looking machine learning from data?”'],
      },
    },
    {
      id: 'l1-s04',
      index: 3,
      stage: 'DISCOVER',
      title: 'Video Introduction',
      studentTitle: 'WATCH LIKE AN AI DETECTIVE',
      objectives: lo1,
      iCan: 'I can listen for how AI learns.',
      strategies: ['Focused listening'],
      recommendedMinutes: 3,
      teacher: {
        time: '3 minutes',
        objectives: lo1,
        strategy: 'Multimedia learning · Focused listening · Retrieval',
        script: [
          'Listen for ONE thing: What does AI learn from?',
          'After the video, check the question together.',
        ],
        expectedAnswers: ['Examples / data'],
        misconceptions: ['AI learns by eating or sleeping like a person.'],
        support: [...supportBase, 'Replay a short section if needed.'],
        challenge: ['Ask: “What kind of examples might a computer use?”'],
      },
    },
    {
      id: 'l1-s05',
      index: 4,
      stage: 'LEARN',
      title: 'How AI Learns',
      studentTitle: 'HOW DOES AI LEARN?',
      objectives: lo1,
      iCan: 'I can explain how AI learns from examples.',
      strategies: ['Explicit instruction'],
      recommendedMinutes: 3,
      teacher: {
        time: '3 minutes',
        objectives: lo1,
        strategy: 'Explicit Instruction · Dual Coding · Guided Questioning',
        script: [
          'AI needs information to learn. We call that information data.',
          'Pictures can be data. Words can be data. Sounds can be data.',
          'AI looks at lots of examples and finds things that are similar.',
          'Those similarities are patterns.',
          'The patterns help AI recognize something new.',
        ],
        expectedAnswers: ['Data'],
        misconceptions: ['AI learns in the same way a child eats or sleeps.'],
        support: supportBase,
        challenge: ['Ask: “Could a sound be data too?”'],
      },
    },
    {
      id: 'l1-s06',
      index: 5,
      stage: 'LEARN',
      title: 'AI Word Lab',
      studentTitle: 'AI WORD LAB',
      objectives: loBoth,
      iCan: 'I can tell what data means.',
      strategies: ['Interactive vocabulary'],
      recommendedMinutes: 2,
      teacher: {
        time: '2 minutes',
        objectives: loBoth,
        strategy: 'Interactive Vocabulary · Retrieval Practice',
        script: [
          'Tap a word to flip the card.',
          'Then check: Can a picture be data?',
        ],
        expectedAnswers: ['Yes — a picture can be data.'],
        misconceptions: ['Data only means numbers.'],
        support: supportBase,
        challenge: ['Ask children to give their own example of data.'],
      },
    },
    {
      id: 'l1-s07',
      index: 6,
      stage: 'PRACTICE',
      title: 'Find the Pattern',
      studentTitle: 'AI DETECTIVE: FIND THE PATTERN!',
      objectives: lo1,
      iCan: 'I can find a pattern.',
      strategies: ['Inquiry'],
      recommendedMinutes: 6,
      teacher: {
        time: '6 minutes',
        objectives: lo1,
        strategy: 'Inquiry Learning · Cooperative Learning',
        script: [
          'Study all the bird pictures.',
          'Talk with your group.',
          'Choose TWO useful patterns.',
        ],
        prompts: [
          'What is the same?',
          'What is different?',
          'Which feature appears on most of the birds?',
        ],
        expectedAnswers: ['wings', 'beaks', 'feathers', 'two legs'],
        misconceptions: ['Colour is a useful pattern for all birds.'],
        support: [...supportBase, 'Reduce to “find ONE pattern” if needed.'],
        challenge: ['Ask groups to name a feature that is NOT the same for every bird.'],
      },
    },
    {
      id: 'l1-s08',
      index: 7,
      stage: 'PRACTICE',
      title: 'Pattern Reveal',
      studentTitle: 'WHAT PATTERNS DID WE FIND?',
      objectives: lo1,
      iCan: 'I can tell a useful pattern from a trick.',
      strategies: ['Misconception check'],
      recommendedMinutes: 2,
      teacher: {
        time: '2 minutes',
        objectives: lo1,
        strategy: 'Student Explanation · Misconception Checking',
        script: [
          'Reveal one pattern at a time after groups share.',
          'Then test the false pattern: “All birds are green.”',
        ],
        expectedAnswers: [
          'Wings, beak, feathers, two legs',
          '“All birds are green” is not a useful pattern.',
        ],
        misconceptions: ['Any similarity is a useful pattern, even if it is not true for many examples.'],
        support: supportBase,
        challenge: ['Ask: “Why did colour not work as a pattern here?”'],
      },
    },
    {
      id: 'l1-s09',
      index: 8,
      stage: 'LEARN',
      title: 'Connect to AI',
      studentTitle: 'YOU JUST THOUGHT LIKE AI!',
      objectives: lo1,
      iCan: 'I can explain how AI learns from examples.',
      strategies: ['Concept consolidation'],
      recommendedMinutes: 4,
      teacher: {
        time: '4 minutes',
        objectives: lo1,
        strategy: 'Concept Consolidation · Guided Questioning',
        script: [
          'We looked at real bird photos — that was our data.',
          'We looked for similarities — we found patterns.',
          'That is how AI learns to recognize a bird.',
        ],
        expectedAnswers: ['DATA', 'PATTERNS'],
        misconceptions: ['The teacher told the computer the answer instead of using examples.'],
        support: supportBase,
        challenge: ['Ask children to retell the three steps in order.'],
      },
    },
    {
      id: 'l1-s10',
      index: 9,
      stage: 'LEARN',
      title: 'Good Data vs Bad Data',
      studentTitle: 'GOOD DATA OR BAD DATA?',
      objectives: lo2,
      iCan: 'I can tell good data from bad data.',
      strategies: ['Compare and contrast'],
      recommendedMinutes: 4,
      teacher: {
        time: '4 minutes',
        objectives: lo2,
        strategy: 'Compare & Contrast · Worked Examples',
        script: [
          'Some examples help Pixel, but some examples confuse Pixel.',
          'Clear, correct, useful examples are good data.',
          'Unclear, wrong, or confusing examples are bad data.',
        ],
        expectedAnswers: [
          'Good data helps AI learn better.',
          'Bad data can confuse AI.',
        ],
        misconceptions: ['Any picture of an animal is useful training data.'],
        support: supportBase,
        challenge: ['Ask: “Which problem is worse — blurry or wrongly labelled?”'],
      },
    },
    {
      id: 'l1-s11',
      index: 10,
      stage: 'PLAY',
      title: 'Data Detective',
      studentTitle: 'DATA DETECTIVE',
      objectives: lo2,
      iCan: 'I can tell good data from bad data.',
      strategies: ['Whole-class response'],
      recommendedMinutes: 5,
      teacher: {
        time: '5 minutes',
        objectives: lo2,
        strategy: 'Gamification · Formative Assessment · Whole-Class Response',
        script: [
          'Class votes Good Data or Bad Data.',
          'Do not reveal until CHECK.',
          'Add a team point if you wish.',
        ],
        expectedAnswers: [
          'R1 Good — clear + correct',
          'R2 Bad — too unclear',
          'R3 Bad — wrong label',
          'R4 Good — clear + correct',
          'R5 Bad — not useful for pets',
          'R6 Good — clear + correct',
        ],
        misconceptions: ['A clear photo is always good data, even with the wrong label.'],
        support: supportBase,
        challenge: ['Ask children to invent a 7th example.'],
      },
    },
    {
      id: 'l1-s12',
      index: 11,
      stage: 'APPLY',
      title: 'Train Pixel',
      studentTitle: 'TRAIN PIXEL!',
      objectives: loBoth,
      iCan: 'I can choose examples that help AI learn.',
      strategies: ['Classification'],
      recommendedMinutes: 4,
      teacher: {
        time: '4 minutes',
        objectives: loBoth,
        strategy: 'Collaborative Problem Solving · Classification',
        script: [
          'Pixel needs to learn what a CAT looks like.',
          'Drag examples into Train or Do Not Use.',
          'We want clear, correct, relevant, varied examples.',
        ],
        expectedAnswers: [
          'Use: clear cats of different types.',
          'Do not use: dog, car, wrongly labelled cat.',
        ],
        misconceptions: ['More pictures is always better, even if they are wrong.'],
        support: [...supportBase, 'Teacher can drag for the class based on group votes.'],
        challenge: ['Ask: “Why do we want more than one kind of cat?”'],
      },
    },
    {
      id: 'l1-s13',
      index: 12,
      stage: 'APPLY',
      title: 'My AI Trainer Challenge',
      studentTitle: 'MY AI TRAINER CHALLENGE',
      objectives: loBoth,
      iCan: 'I can explain how AI learns from examples.',
      strategies: ['Independent practice'],
      recommendedMinutes: 3,
      teacher: {
        time: '3 minutes',
        objectives: loBoth,
        strategy: 'Independent Practice · Formative Assessment',
        script: [
          'This is individual thinking.',
          'Students may answer with fingers 1, 2, or 3, or mini whiteboards.',
        ],
        expectedAnswers: ['1. Data', '2. Clear correctly labelled dog', '3. patterns'],
        misconceptions: [],
        support: [...supportBase, 'Reduce to two choices if needed.'],
        challenge: ['Ask for a reason in a full sentence.'],
      },
    },
    {
      id: 'l1-s14',
      index: 13,
      stage: 'APPLY',
      title: 'Bonus Challenge',
      studentTitle: 'BONUS AI TRAINER CHALLENGE',
      objectives: lo2,
      iCan: 'I can tell when data is missing variety.',
      strategies: ['Stretch thinking'],
      recommendedMinutes: 1,
      teacher: {
        time: '1 minute',
        objectives: lo2,
        strategy: 'Higher-Order Thinking · Differentiation',
        script: [
          'Pixel learns only from these orange cats.',
          'What might happen when Pixel sees a cat that looks different?',
          'Do not use the word “bias” yet.',
        ],
        expectedAnswers: [
          'Pixel might become confused because it needs more different examples.',
        ],
        misconceptions: ['AI will always recognise every new example immediately.'],
        support: supportBase,
        challenge: ['Which other cat pictures would you add?'],
      },
    },
    {
      id: 'l1-s15',
      index: 14,
      stage: 'REFLECT',
      title: 'Exit Ticket',
      studentTitle: 'BEFORE YOU LEAVE THE AI LAB...',
      objectives: loBoth,
      iCan: 'I can explain how AI learns from examples.',
      strategies: ['Exit ticket'],
      recommendedMinutes: 2,
      teacher: {
        time: '2 minutes',
        objectives: loBoth,
        strategy: 'Exit Ticket · Retrieval Practice · Self-Assessment',
        script: [
          'Ask one question at a time.',
          'Reveal a suggested answer after thinking time.',
          'Then do the feelings check.',
        ],
        expectedAnswers: [
          'AI learns from data/examples and patterns.',
          'Good data helps AI learn better/correctly.',
          'Bad data can confuse AI.',
        ],
        misconceptions: [],
        support: supportBase,
        challenge: ['Ask a child to teach Pixel in one sentence.'],
      },
    },
    {
      id: 'l1-s16',
      index: 15,
      stage: 'REFLECT',
      title: 'Mission Complete',
      studentTitle: 'MISSION 1 COMPLETE!',
      objectives: loBoth,
      iCan: 'I can teach Pixel how to learn.',
      strategies: ['Recap'],
      recommendedMinutes: 1,
      teacher: {
        time: '1 minute',
        objectives: loBoth,
        strategy: 'Celebration · Recap',
        script: [
          'Celebrate the AI Trainer badge.',
          'Preview next mission: Clear instructions matter.',
        ],
        expectedAnswers: [],
        misconceptions: [],
        support: supportBase,
        challenge: [],
      },
    },
  ],
};
